name: CI

on:
  push:
    branches: [main]
    tags-ignore:
      - 'v*'

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: Dotnet Restore
        run: dotnet restore

      - name: Dotnet Build
        run: dotnet build --configuration Release --no-restore

      - name: Dotnet Test
        run: dotnet test --configuration Release --no-build --verbosity normal --logger "console;verbosity=detailed"
